@extends('layouts.master')

@section('title', 'Privacy Policy')

@section('content')
    <div class="wpb_text_column wpb_content_element ">
        <div class="wpb_wrapper">
            <h3 style="color: #cc0000; font-size: 20px;"><strong>Privacy Policy</strong></h3>

        </div>
    </div>
    <div class="wpb_text_column wpb_content_element ">
        <div class="wpb_wrapper">
            <p>Effective date: February 12, 2019</p>
            <p>&nbsp;</p>
            <p>ASIAL10N Pte. Ltd. (&#8220;us&#8221;, &#8220;we&#8221;, or &#8220;our&#8221;) operates the www.asialion.com website (hereinafter referred to as the &#8220;Service&#8221;).</p>
            <p>&nbsp;</p>
            <p>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
            <p>&nbsp;</p>
            <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from www.asialion.com</p>

        </div>
    </div><div class="vc_row wpb_row section vc_inner  grid_section" style=' text-align:left;'><div class=" section_inner clearfix"><div class='section_inner_margin clearfix'><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner"><div class="wpb_wrapper">
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Definitions</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="padding-left: 40px;"><strong>Service</strong></p>
                                    <p style="padding-left: 40px;">Service is the www.asialion.com website operated by ASIAL10N Pte. Ltd.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Personal Data</strong></p>
                                    <p style="padding-left: 40px;">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Usage Data</strong></p>
                                    <p style="padding-left: 40px;">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Cookies</strong></p>
                                    <p style="padding-left: 40px;">Cookies are small files stored on your device (computer or mobile device).</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Data Controller</strong></p>
                                    <p style="padding-left: 40px;">Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
                                    <p style="padding-left: 40px;">For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Data Processors (or Service Providers)</strong></p>
                                    <p style="padding-left: 40px;">Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>
                                    <p style="padding-left: 40px;">We may use the services of various Service Providers in order to process your data more effectively.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Data Subject (or User)</strong></p>
                                    <p style="padding-left: 40px;">Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Information Collection and Use</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="padding-bottom: 15px;">We collect several different types of information for various purposes to provide and improve our Service to you.</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000;"><strong>Types of Data Collected</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p><strong><em>Personal Data</em></strong><br />
                                        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&#8220;Personal Data&#8221;). Personally identifiable information may include, but is not limited to:</p>
                                    <p>&nbsp;</p>
                                    <ul>
                                        <li>Email address</li>
                                        <li>First name and last name</li>
                                        <li>Cookies and Usage Data</li>
                                    </ul>
                                    <p>&nbsp;</p>
                                    <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.</p>
                                    <p>&nbsp;</p>
                                    <p><em><strong>Usage Data</strong></em><br />
                                        We may also collect information on how the Service is accessed and used (&#8220;Usage Data&#8221;). This Usage Data may include information such as your computer&#8217;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                                    <p>&nbsp;</p>
                                    <p><em><strong>Tracking Cookies Data</strong></em><br />
                                        We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
                                    <p>&nbsp;</p>
                                    <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</p>
                                    <p>&nbsp;</p>
                                    <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
                                    <p>&nbsp;</p>
                                    <p>Examples of Cookies we use:</p>
                                    <p>&nbsp;</p>
                                    <ul>
                                        <li><strong>Session Cookies</strong>. We use Session Cookies to operate our Service.</li>
                                        <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                                        <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
                                    </ul>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Use of Data</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="padding-bottom: 20px;">ASIAL10N Pte. Ltd. uses the collected data for various purposes:</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <ul>
                                        <li>To provide and maintain our Service</li>
                                        <li>To notify you about changes to our Service</li>
                                        <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                                        <li>To provide customer support</li>
                                        <li>To gather analysis or valuable information so that we can improve our Service</li>
                                        <li>To monitor the usage of our Service</li>
                                        <li>To detect, prevent and address technical issues</li>
                                        <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
                                    </ul>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>If you are from the European Economic Area (EEA), ASIAL10N Pte. Ltd. legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
                                    <p>&nbsp;</p>
                                    <p>ASIAL10N Pte. Ltd. may process your Personal Data because:</p>
                                    <p>&nbsp;</p>
                                    <ul>
                                        <li>We need to perform a contract with you</li>
                                        <li>You have given us permission to do so</li>
                                        <li>The processing is in our legitimate interests and it is not overridden by your rights</li>
                                        <li>To comply with the law</li>
                                    </ul>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Retention of Data</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>ASIAL10N Pte. Ltd. will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.</p>
                                    <p>&nbsp;</p>
                                    <p>ASIAL10N Pte. Ltd. will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Transfer of Data</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
                                    <p>&nbsp;</p>
                                    <p>If you are located outside Singapore and choose to provide information to us, please note that we transfer the data, including Personal Data, to Singapore and process it there.</p>
                                    <p>&nbsp;</p>
                                    <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                                    <p>&nbsp;</p>
                                    <p>ASIAL10N Pte. Ltd. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 15px 0;"><strong>Disclosure of Data</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p><span style="color: #cc0000;"><strong>Business Transaction</strong></span></p>
                                    <p>If ASIAL10N Pte. Ltd. is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                                    <p>&nbsp;</p>
                                    <p><strong><span style="color: #cc0000;">Disclosure for Law Enforcement</span></strong></p>
                                    <p>Under certain circumstances, ASIAL10N Pte. Ltd. may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                                    <p>&nbsp;</p>
                                    <p><strong><span style="color: #cc0000;">Legal Requirements</span></strong></p>
                                    <p>ASIAL10N Pte. Ltd. may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
                                    <ul>
                                        <li>To comply with a legal obligation</li>
                                        <li>To protect and defend the rights or property of ASIAL10N Pte. Ltd.</li>
                                        <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                                        <li>To protect the personal safety of users of the Service or the public</li>
                                        <li>To protect against legal liability</li>
                                    </ul>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Security of Data</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Our Policy on &#8220;Do Not Track&#8221; Signals under the California Online Protection Act (CalOPPA)</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>We do not support Do Not Track (&#8220;DNT&#8221;). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
                                    <p>&nbsp;</p>
                                    <p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Your Data Protection Rights under the General Data Protection Regulation (GDPR)</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. ASIAL10N Pte. Ltd. aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.</p>
                                    <p>&nbsp;</p>
                                    <p>If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
                                    <p>&nbsp;</p>
                                    <p>In certain circumstances, you have the following data protection rights:</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>The right to access, update or delete the information we have on you.</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where ASIAL10N Pte. Ltd. relied on your consent to process your personal information.</p>
                                    <p>&nbsp;</p>
                                    <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
                                    <p>&nbsp;</p>
                                    <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Service Providers</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>We may employ third party companies and individuals to facilitate our Service (&#8220;Service Providers&#8221;), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
                                    <p>&nbsp;</p>
                                    <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
                                    <p>&nbsp;</p>
                                    <p><strong><span style="color: #cc0000;">Analytics</span></strong><br />
                                        We may use third-party Service Providers to monitor and analyse the use of our Service.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Google Analytics</strong><br />
                                        Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.<br />
                                        You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.<br />
                                        For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a></p>
                                    <p>&nbsp;</p>
                                    <p><span style="color: #cc0000;"><strong>Behavioral Remarketing</strong></span><br />
                                        ASIAL10N Pte. Ltd. uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Google Ads (AdWords)</strong><br />
                                        Google Ads (AdWords) remarketing service is provided by Google Inc.<br />
                                        You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the Google Ads Settings page: <a href="http://www.google.com/settings/ads">http://www.google.com/settings/ads</a><br />
                                        Google also recommends installing the Google Analytics Opt-out Browser Add-on &#8211; <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a> &#8211; for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.<br />
                                        For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a></p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Twitter</strong><br />
                                        Twitter remarketing service is provided by Twitter Inc.<br />
                                        You can opt-out from Twitter&#8217;s interest-based ads by following their instructions: <a href="https://support.twitter.com/articles/20170405">https://support.twitter.com/articles/20170405</a><br />
                                        You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page: <a href="https://twitter.com/privacy">https://twitter.com/privacy</a></p>
                                    <p>&nbsp;</p>
                                    <p style="padding-left: 40px;"><strong>Facebook</strong><br />
                                        Facebook remarketing service is provided by Facebook Inc.<br />
                                        You can learn more about interest-based advertising from Facebook by visiting this page: <a href="https://www.facebook.com/help/164968693837950">https://www.facebook.com/help/164968693837950</a><br />
                                        To opt-out from Facebook&#8217;s interest-based ads, follow these instructions from Facebook: <a href="https://www.facebook.com/help/568137493302217">https://www.facebook.com/help/568137493302217</a><br />
                                        Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA <a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a>, the Digital Advertising Alliance of Canada in Canada <a href="http://youradchoices.ca/">http://youradchoices.ca/</a> or the European Interactive Digital Advertising Alliance in Europe <a href="http://www.youronlinechoices.eu/">http://www.youronlinechoices.eu/</a>, or opt-out using your mobile device settings.<br />
                                        For more information on the privacy practices of Facebook, please visit Facebook&#8217;s Data Policy: <a href="https://www.facebook.com/privacy/explanation">https://www.facebook.com/privacy/explanation</a></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Links to Other Sites</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&#8217;s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
                                    <p>&nbsp;</p>
                                    <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Children&#8217;s Privacy</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>Our Service does not address anyone under the age of 18 (&#8220;Children&#8221;).</p>
                                    <p>&nbsp;</p>
                                    <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Changes to This Privacy Policy</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
                                    <p>&nbsp;</p>
                                    <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the &#8220;effective date&#8221; at the top of this Privacy Policy.</p>
                                    <p>&nbsp;</p>
                                    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p style="color: #cc0000; font-size: 18px; padding: 30px 0 0 0;"><strong>Contact Us</strong></p>

                                </div>
                            </div>
                            <div class="wpb_text_column wpb_content_element ">
                                <div class="wpb_wrapper">
                                    <p>If you have any questions about this Privacy Policy, please contact us:</p>
                                    <p>&nbsp;</p>
                                    <ul style="padding-bottom: 50px;">
                                        <li>By email: <a href="mailto:hithere@l10n.asia">hithere@l10n.asia</a></li>
                                    </ul>
@stop